void print_alphabet(void);
void _putchar(char);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int _abs(int);
void times_table(void);
int print_sign(int n);
int print_last_digit(int);
int add(int, int);
